import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  constructor(private http :HttpClient) { }

  getProducts(){
return this.http.get('https://freeapi.miniprojectideas.com/api/amazon/GetAllProducts')
  }

  myarray=[
    {
      "productId": 364,
      "productSku": "KJBL C100SI Wired Ic, JBL Pure Bass Sound, One Butto",
      "productName": "KALL N9 Tablet",
      "productPrice": 150,
      "productShortName": "ZEBRONICS Thunder",
      "productDescription": "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button Multi-function Remote, Premium Metallic FinisJBL C100SI Wired In Ear Headphones",
      "createdDate": "2024-07-15T15:10:48.143",
      "deliveryTimeSpan": "5 days",
      "categoryId": 3,
      "productImageUrl": "https://m.media-amazon.com/images/I/618Z0eTNM6L._AC_UY327_FMwebp_QL65_.jpg",
      "categoryName": "Tablet"
    },
    {
      "productId": 405,
      "productSku": "test1",
      "productName": "Xiaomi Mi 12 Ultra",
      "productPrice": 90,
      "productShortName": "Xiaomi Phone",
      "productDescription": "test",
      "createdDate": "2024-09-22T16:44:47.393",
      "deliveryTimeSpan": "1 Days",
      "categoryId": 1,
      "productImageUrl": "https://pixlr.com/images/index/ai-image-generator-one.webp",
      "categoryName": "Mobile"
    },
    {
      "productId": 336,
      "productSku": "Xiaomi Mi 12 Ultra",
      "productName": "Xiaomi Mi 12 Ultra",
      "productPrice": 850,
      "productShortName": "Xiaomi Phone",
      "productDescription": "Xiaomi Mi 12 Ultra",
      "createdDate": "2024-06-06T11:53:30.017",
      "deliveryTimeSpan": "10 Days",
      "categoryId": 4,
      "productImageUrl": "https://cdn.dxomark.com/wp-content/uploads/medias/post-121010/Xiaomi-12S-Ultra-featured-image-packshot-review.jpg",
      "categoryName": "Laptop"
    },
    {
      "productId": 429,
      "productSku": "ipo7kh",
      "productName": "Xiaomi Mi 12 Ultra",
      "productPrice": 850,
      "productShortName": "Xiaomi Phone",
      "productDescription": "ytyyu",
      "createdDate": "2024-10-04T13:01:21.79",
      "deliveryTimeSpan": "10 Days",
      "categoryId": 9,
      "productImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrWftdBJV2Q9HHuWroRuqFzRWGPZFfZa5bDw&s",
      "categoryName": "mobile1"
    },
    {
      "productId": 406,
      "productSku": "Mini Project",
      "productName": "Xiaomi Mi 12 Ultra",
      "productPrice": 850,
      "productShortName": "Xiaomi Phone",
      "productDescription": "Mini Project",
      "createdDate": "2024-09-22T22:59:09.037",
      "deliveryTimeSpan": "10 Days",
      "categoryId": 9,
      "productImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsfRapoTS7o18tR7CWPdvX98kpqN0G2S9LeQ&s",
      "categoryName": "mobile1"
    },
    {
      "productId": 426,
      "productSku": "Shomi Matephone ",
      "productName": "Xiaomi Mi 12 Ultra",
      "productPrice": 850,
      "productShortName": "Xiaomi Phone",
      "productDescription": "uyyyy",
      "createdDate": "2024-10-04T12:03:02.263",
      "deliveryTimeSpan": "10 Days",
      "categoryId": 9,
      "productImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrWftdBJV2Q9HHuWroRuqFzRWGPZFfZa5bDw&s",
      "categoryName": "mobile1"
    },
    {
      "productId": 23,
      "productSku": "XiaomiA1",
      "productName": "Xiaomi A1",
      "productPrice": 200,
      "productShortName": "Xia A1",
      "productDescription": "Newest and fasetst edition of the A-line by Xiaomi",
      "createdDate": "2023-07-19T19:31:17.423",
      "deliveryTimeSpan": "1 day",
      "categoryId": 4,
      "productImageUrl": "https://beebom.com/wp-content/uploads/2017/12/Mi-A1-Review.jpg?w=750&quality=75",
      "categoryName": "Laptop"
    },
    {
      "productId": 438,
      "productSku": "u2",
      "productName": "T-shirt-black",
      "productPrice": 150,
      "productShortName": "T-shirt",
      "productDescription": "T-shirt - S size White colo",
      "createdDate": "2024-11-26T18:52:53.97",
      "deliveryTimeSpan": "2-3 days",
      "categoryId": 63,
      "productImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY8BibRWYE-MvHbJ2QWkFmzVZwNRevriwGHQ&s",
      "categoryName": "Fruits & Vegetables"
    },
    {
      "productId": 376,
      "productSku": "2662652366",
      "productName": "EOS R50 Body",
      "productPrice": 454,
      "productShortName": "test",
      "productDescription": "<h3><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">Capture the Moment Just as You Imagine It</span></h3><p><span style=\"background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);\">The EOS R50 camera makes photography fun, simple, and convenient with intuitive photo functions that capture beautiful images automatically, just as you imagine them. A host of video functions such as 6K oversampled 4K 30p capture and Dual Pixel</span></p><p></p>",
      "createdDate": "2024-08-06T22:53:21.397",
      "deliveryTimeSpan": "10-15 day",
      "categoryId": 2,
      "productImageUrl": "https://s7d1.scene7.com/is/image/canon/5812C002_eos-r50-body-white_primary?fmt=webp-alpha&wid=800",
      "categoryName": "Camera"
    },
    {
      "productId": 439,
      "productSku": "str",
      "productName": "Strawberry",
      "productPrice": 70,
      "productShortName": "Strawberry",
      "productDescription": "Strawberry is good for health. and Its have is expencive",
      "createdDate": "2024-11-27T02:08:41.53",
      "deliveryTimeSpan": "1 day",
      "categoryId": 55,
      "productImageUrl": "https://www.bigbasket.com/media/uploads/p/l/10000263_13-fresho-strawberry.jpg",
      "categoryName": "Celulares"
    },
    {
      "productId": 369,
      "productSku": "Sony ZV-1 Digital Camera Advanced Compacts Cameras Only",
      "productName": "Sony ZV-1 Digital Camera Advanced",
      "productPrice": 79990,
      "productShortName": "Sony ZV-1 Digital Camera Advanced",
      "productDescription": "Sony ZV-1 Digital Camera Advanced Compacts Cameras Only",
      "createdDate": "2024-07-15T16:00:42.727",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 2,
      "productImageUrl": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTofEiBrCz1y0WD917lS6X5XJK6b5GcUsqNce2MgI5S9PkoWxOQIL7SpOxaA-OVeu-giIoBn-TE_hPUUxw2bAhIBfd2FGMlnBZvMAGFpJv0P9IuAZiRPcBY",
      "categoryName": "Camera"
    },
    {
      "productId": 368,
      "productSku": "Sony Alpha ILCE-6100Y",
      "productName": "Sony Alpha ILCE-6100Y",
      "productPrice": 990,
      "productShortName": "Sony Alpha ILCE-6100Y",
      "productDescription": "Sigma 24-70Mm F/2.8 Dg Dn Full Frame Lens for Sony E Mount Mirror-Less Cameras - Black",
      "createdDate": "2024-07-15T15:58:36.743",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 2,
      "productImageUrl": "https://m.media-amazon.com/images/I/41w9-ptS-uL._SY300_SX300_QL70_FMwebp_.jpg",
      "categoryName": "Camera"
    },
    {
      "productId": 435,
      "productSku": "Sk-1",
      "productName": "Samsung Ultra",
      "productPrice": 85,
      "productShortName": "SM Phone",
      "productDescription": "Test Product",
      "createdDate": "2024-11-11T06:21:07.8",
      "deliveryTimeSpan": "10 Days",
      "categoryId": 4,
      "productImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0praxNFT7dTQYuQlpiE9nl6gbXzpnY0kSRg&s",
      "categoryName": "Laptop"
    },
    {
      "productId": 356,
      "productSku": "SAMSUNG Galaxy Tab A9 Plus Wi-Fi+5G Android Tablet (11 Inch, 8GB RAM, 128GB ROM, Silver)",
      "productName": "SAMSUNG Galaxy Tab A9 Plus Wi-Fi+5G Android Tablet",
      "productPrice": 899,
      "productShortName": "SAMSUNG Galaxy Tab A9 Plus Wi-Fi+5G Android Tablet",
      "productDescription": "Prepare to be captivated by the stunning visuals on the 11-inch 1920 x 1200 (WUXGA) TFT LCD display. With a refresh rate of up to 90Hz, every image, video, and game comes to life with impeccable clarity and fluidity. Whether you're binge-watching your favorite shows or immersing yourself in the latest games, the display on this tab delivers an unrivaled visual experience..",
      "createdDate": "2024-07-15T07:51:07.8",
      "deliveryTimeSpan": "5 days",
      "categoryId": 3,
      "productImageUrl": "https://static.javatpoint.com/computer/images/what-is-a-tablet.png",
      "categoryName": "Tablet"
    },
    {
      "productId": 360,
      "productSku": "Samsung Galaxy Book3 Pro ",
      "productName": "Samsung Galaxy Book3 Pro ",
      "productPrice": 119990,
      "productShortName": "Samsung Galaxy Book3 Pro ",
      "productDescription": "Samsung Galaxy Book3 Pro 360 Intel 13th Gen i7 EvoTM 40.62cm(16) Touchscreen 2-in-1 3K Display, 120Hz, Thin & Light Laptop(16 GB/1 TB SSD/Windows 11/MS Office/S-Pen/Graphite/1.6Kg), NP960QFG-KA3IN",
      "createdDate": "2024-07-15T14:59:15.047",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 4,
      "productImageUrl": "https://m.media-amazon.com/images/I/31aPzW9atKL._SX300_SY300_QL70_FMwebp_.jpg",
      "categoryName": "Laptop"
    },
    {
      "productId": 343,
      "productSku": "Oppo Find X5 Pro",
      "productName": "Oppo Find X5 Pro",
      "productPrice": 35000,
      "productShortName": "Oppo Find X5 Pro",
      "productDescription": "Oppo Find X5 Pro",
      "createdDate": "2024-06-06T12:02:50.927",
      "deliveryTimeSpan": "4",
      "categoryId": 1,
      "productImageUrl": "https://image.oppo.com/content/dam/oppo/en/mkt/newsroom/press/oppo-launches-find-x-five-series/img-01.jpg.thumb.webp",
      "categoryName": "Mobile"
    },
    {
      "productId": 357,
      "productSku": "OnePlus Pad Go 28.82 cm",
      "productName": "OnePlus Pad Go 28.82 cm",
      "productPrice": 39999,
      "productShortName": "OnePlus Pad Go 28.82 cm",
      "productDescription": "OnePlus Pad Go 28.82 cm (11.35 inches) 8 GB RAM, 128 GB, Twin Mint, Wi-Fi Tablet, OPD2305 IN",
      "createdDate": "2024-07-15T07:56:52.063",
      "deliveryTimeSpan": "5 days",
      "categoryId": 3,
      "productImageUrl": "https://static.javatpoint.com/computer/images/what-is-a-tablet.png",
      "categoryName": "Tablet"
    },
    {
      "productId": 365,
      "productSku": "Nikon Digital Camera",
      "productName": "Nikon Digital Camera",
      "productPrice": 999,
      "productShortName": "Nikon Digital Camera",
      "productDescription": "Nikon Digital Camera Z 6III Body with NIKKOR Z 24-120mm f/4 S Lens - Full-Frame Mirrorless, 24.5MP, 4K UHD Video, Fast Autofocus, in-Body Stabilization",
      "createdDate": "2024-07-15T15:52:33.673",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 2,
      "productImageUrl": "https://m.media-amazon.com/images/G/31/img24/camera/july/pd/tea-newlaunch/Launch_440x460_2._CB569410640_.png",
      "categoryName": "Camera"
    },
    {
      "productId": 409,
      "productSku": "A19-ty",
      "productName": "maize",
      "productPrice": 19000,
      "productShortName": "ms",
      "productDescription": "for food especially ugali",
      "createdDate": "2024-10-02T14:25:58.367",
      "deliveryTimeSpan": "4-5day",
      "categoryId": 23,
      "productImageUrl": "https://m.media-amazon.com/images/I/41w9-ptS-uL._SY300_SX300_QL70_FMwebp_.jpg",
      "categoryName": "cars"
    },
    {
      "productId": 341,
      "productSku": "Motorola Edge 30 Pro",
      "productName": "Motorola Edge 3100 Pro",
      "productPrice": 67000,
      "productShortName": "Motorola Edge 330 Pro",
      "productDescription": "Motorola Edge 30 Pro",
      "createdDate": "2024-06-06T12:01:09.81",
      "deliveryTimeSpan": "5 Days",
      "categoryId": 1,
      "productImageUrl": "https://motorolaph.vtexassets.com/arquivos/ids/155434/motorola-edge30-pro-pdp-render-Cosmos-3-we9qp5nm.png?v=637842474822470000",
      "categoryName": "Mobile"
    },
    {
      "productId": 441,
      "productSku": "wm1",
      "productName": "Water Melon",
      "productPrice": 20,
      "productShortName": "Melon",
      "productDescription": "Its good for health",
      "createdDate": "2024-12-12T03:40:50.663",
      "deliveryTimeSpan": "1 Days",
      "categoryId": 63,
      "productImageUrl": "https://blog.artsper.com/wp-content/uploads/2018/08/Vik-muniz-van-gogh-min-2.jpg",
      "categoryName": "Fruits & Vegetables"
    },
    {
      "productId": 374,
      "productSku": "LGCAM",
      "productName": "LG Cam 12 Pro",
      "productPrice": 23000,
      "productShortName": "LGCAM",
      "productDescription": "This a LG cam",
      "createdDate": "2024-07-16T13:41:47.207",
      "deliveryTimeSpan": "5 days",
      "categoryId": 1,
      "productImageUrl": "https://gppro.in/wp-content/uploads/2021/11/SONY-ILCE-A7SM3-CAMERA-GP001072-5.jpg",
      "categoryName": "Mobile"
    },
    {
      "productId": 338,
      "productSku": "LG V90 ThinQ",
      "productName": "LG V90 ThinQ",
      "productPrice": 38000,
      "productShortName": "LG V90 ThinQ",
      "productDescription": "LG V90 ThinQ",
      "createdDate": "2024-06-06T11:58:38.68",
      "deliveryTimeSpan": "3",
      "categoryId": 1,
      "productImageUrl": "https://i.pinimg.com/736x/ce/bc/d7/cebcd741bf39058386b280fab5af1e75.jpg",
      "categoryName": "Mobile"
    },
    {
      "productId": 363,
      "productSku": "KJBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Butto",
      "productName": "KALL N9 3G Calling Tablet (2GB RAM, 16GB Storage) (Black)",
      "productPrice": 990,
      "productShortName": "JBL C100SI Wired",
      "productDescription": "JBL C100SI Wired In Ear Headphones with Mic, JBL Pure Bass Sound, One Button Multi-function Remote, Premium Metallic FinisJBL C100SI Wired In Ear Headphones",
      "createdDate": "2024-07-15T15:08:42.77",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 6,
      "productImageUrl": "https://m.media-amazon.com/images/I/61s-3q6CYxL._AC_UY327_FMwebp_QL65_.jpg",
      "categoryName": "headphones"
    },
    {
      "productId": 362,
      "productSku": "KALL N9 3G Calling Tablet (2GB RAM, 16GB Storage) (Black)",
      "productName": "KALL N9 3G Calling Tablet (2GB RAM, 16GB Storage) (Black)",
      "productPrice": 70990,
      "productShortName": "IKALL N9 3G Calling Tablet",
      "productDescription": "AKALL N9 3G Calling Tablet (2GB RAM, 16GB Storage) (Black)",
      "createdDate": "2024-07-15T15:03:45.767",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 3,
      "productImageUrl": "https://m.media-amazon.com/images/I/7185GL6hPlL._AC_UY327_FMwebp_QL65_.jpg",
      "categoryName": "Tablet"
    },
    {
      "productId": 353,
      "productSku": "HD Camera 2024 for Android",
      "productName": "HD Camera 2024 for Android",
      "productPrice": 100000,
      "productShortName": "HD Camera 2024 for Android",
      "productDescription": "A Free and professional DSLR camera app for android. YouA could experience DSLR camera features like a real canon camera as manual control, HDR, slow shutter, and 4K time lapse. HD camera Pro also supports RAW photos and 4K videos.",
      "createdDate": "2024-07-15T07:25:45.287",
      "deliveryTimeSpan": "3 days",
      "categoryId": 2,
      "productImageUrl": "https://play-lh.googleusercontent.com/MM_V6I1jyYXEJKRwcd9-3vog3d0ir4u3meM-n4SV204dayBaeHkdkhpipC83fumaYA=w240-h480-rw",
      "categoryName": "Camera"
    },
    {
      "productId": 366,
      "productSku": "GoPro HERO10 Black",
      "productName": "GoPro HERO10 Black",
      "productPrice": 27490,
      "productShortName": "GoPro HERO10 Black",
      "productDescription": "GoPro HERO10 Black - Waterproof Action Camera with Front LCD and Touch Rear Screens, 5.3K60 Ultra HD Video, Optical 1X and Digital 4X 23MP Photos (1 Year INTL Warranty + 1 Year in Warranty)",
      "createdDate": "2024-07-15T15:54:54.747",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 2,
      "productImageUrl": "https://m.media-amazon.com/images/I/41quDWydN3L._SY300_SX300_QL70_FMwebp_.jpg",
      "categoryName": "Camera"
    },
    {
      "productId": 354,
      "productSku": "Canon EOS 3000D DSLR Camera",
      "productName": "Canon EOS 3000D DSLR Camera 1 Body, 18 - 55 mm Lens  (Black)",
      "productPrice": 29990,
      "productShortName": "Canon EOS 3000D DSLR Camera",
      "productDescription": "If you are a photography enthusiast, then the Canon EOS 3000D DSLR Camera is a must-have gadget. Featuring an 18 MP (APS-C) CMOS sensor and the DIGIC 4+ imaging processor, you can capture amazing photos of your subject at all times, even in low-light conditions. Moreover, the remote Live View function lets you control this camera remotely using your smartphone so you can capture amazing photos even from a distance.",
      "createdDate": "2024-07-15T07:37:30.887",
      "deliveryTimeSpan": "5 days",
      "categoryId": 2,
      "productImageUrl": "https://cdn.mos.cms.futurecdn.net/Ekc54rx2YMgRt5ycD5KYf5.jpg",
      "categoryName": "Camera"
    },
    {
      "productId": 442,
      "productSku": "wb",
      "productName": "Water Bottle",
      "productPrice": 50,
      "productShortName": "Bottle",
      "productDescription": "It keeps water fresh ",
      "createdDate": "2024-12-12T03:45:22.967",
      "deliveryTimeSpan": "2 Days",
      "categoryId": 33,
      "productImageUrl": "https://sf.ezoiccdn.com/ezoimgfmt/eatsleepwander.com/wp-content/uploads/2023/01/HOTEL-STYLE-SHEETS-40.jpg?ezimgfmt=ngcb1/notWebP",
      "categoryName": "bottles"
    },
    {
      "productId": 27,
      "productSku": "iphone Camera",
      "productName": "iphone",
      "productPrice": 15000,
      "productShortName": "BHIM",
      "productDescription": "Lorem",
      "createdDate": "2023-08-02T17:44:25.557",
      "deliveryTimeSpan": "15 Days",
      "categoryId": 10,
      "productImageUrl": "https://i.pinimg.com/1200x/e7/5d/db/e75ddbda351d44e24b6b8099fa200aad.jpg",
      "categoryName": "Iphone"
    },
    {
      "productId": 361,
      "productSku": "ASUS TUF Gaming F17 (2022)",
      "productName": "ASUS TUF Gaming F17 (2022)",
      "productPrice": 70990,
      "productShortName": "ASUS TUF Gaming F17 (2022)",
      "productDescription": "ASUS TUF Gaming F17 (2022) Intel Core i5-12500H Gaming Laptop,17.3(43.94 cms) FHD 144Hz, RTX 3050 4GB GPU, (16GB RAM /512GB SSD/90WHr Battery/Windows 11/Gray/2.6 Kg), FX707ZC4-HX067W",
      "createdDate": "2024-07-15T15:01:39.133",
      "deliveryTimeSpan": "5-7 days",
      "categoryId": 4,
      "productImageUrl": "https://m.media-amazon.com/images/I/41m6q3pDQbL._SX300_SY300_QL70_FMwebp_.jpg",
      "categoryName": "Laptop"
    },
    {
      "productId": 358,
      "productSku": "Acer [Smartchoice] Aspire Lite",
      "productName": "Acer [Smartchoice] Aspire Lite",
      "productPrice": 27990,
      "productShortName": "Acer [Smartchoice] Aspire Lite",
      "productDescription": "Acer [Smartchoice] Aspire Lite AMD Ryzen 3 5300U Premium Thin and Light Laptop (Windows 11 Home/8 GB RAM/512 GB SSD) AL15-41 with 39.62 Full HD Display, Metal Body, Steel Gray, 1.6 KG",
      "createdDate": "2024-07-15T14:54:45.803",
      "deliveryTimeSpan": "1-2 days",
      "categoryId": 4,
      "productImageUrl": "https://m.media-amazon.com/images/I/41qGPk4nUML._SX300_SY300_QL70_FMwebp_.jpg",
      "categoryName": "Laptop"
    },
    {
      "productId": 359,
      "productSku": "Samsung Galaxy Book2 (NP750)",
      "productName": "Samsung Galaxy Book2 (NP750)",
      "productPrice": 64849,
      "productShortName": "Acer [Smartchoice] Aspire Lite",
      "productDescription": "Samsung Galaxy Book2 (NP750) Intel 12th Gen core i7 39.6cm (15.6) FHD Thin & Light Laptop (16 GB/512 GB/Windows 11/MS Office/Backlit Keyboard/Fingerprint Reader/Silver/1.55Kg), NP750XED-KC2IN",
      "createdDate": "2024-07-15T14:56:43.823",
      "deliveryTimeSpan": "1-2 days",
      "categoryId": 4,
      "productImageUrl": "https://m.media-amazon.com/images/I/41KhXf3htkL._SX300_SY300_QL70_FMwebp_.jpg",
      "categoryName": "Laptop"
    }
  ]

}
